import Foundation

/// Where the app talks to — owned by this repository, not injected by a build service.
///
/// `Config.swift` is regenerated by Rork at build time, so builds made anywhere else
/// (Xcode, GitHub Actions) would get empty strings and a dead app. These values are
/// the same ones the Lovable web app ships in its public bundle:
/// - The Supabase publishable key is the `anon` role. It is meant to be public;
///   every row is protected by RLS (`auth.uid() = user_id`).
/// - No secret (AI keys etc.) may ever be placed here. AI goes through the web
///   server (`/api/native-fn`), which holds the keys.
enum AppConfig {
    /// The published Lovable web app. Its server hosts `/api/native-fn`.
    nonisolated static let webBaseURL = URL(string: "https://catchwords.lovable.app")!

    nonisolated static let supabaseURL = "https://arjicopbmvseztldpxpk.supabase.co"
    nonisolated static let supabasePublishableKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFyamljb3BibXZzZXp0bGRweHBrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODIxMjUwODQsImV4cCI6MjA5NzcwMTA4NH0.ZzTgNSzT8QWZ2QIeBUVjx_UONYMl-R1Iak9oRAJMknQ"
}
